services:
  mongo-service:
    image: mongo:latest # Pull the latest mongodb image
    ports:
      - "27017:27017" # Expose port 27017
    volumes:
      - mongo_data:/data/db
  user-service:
    build: ./user_service  # Path to your user_service directory
    ports:
      - "8001:8001"  # Expose port 8001 inside the container to 8001 on your host
    depends_on:
      - mongo-service
  api-gateway:
    build: ./api_gateway  # Path to your api directory
    ports:
      - "8000:8000"  # Expose port 8000 inside the container to 8000 on your host
    depends_on:
      - mongo-service
      - user-service  # Ensure User Service starts before API Gateway

volumes:
  mongo_data: